<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ProtectedDataVersion>8.0.0</ProtectedDataVersion>
    <ThreadingAccessControlVersion>8.0.0</ThreadingAccessControlVersion>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="$(ProtectedDataVersion)" />
    <PackageReference Include="System.Threading.AccessControl" Version="$(ThreadingAccessControlVersion)" />
  </ItemGroup>

</Project>
